export enum MedicalSpecialization {
  GENERAL_PRACTICE = 'general_practice',
  CARDIOLOGY = 'cardiology',
  NEUROLOGY = 'neurology',
  GASTROENTEROLOGY = 'gastroenterology',
  PULMONOLOGY = 'pulmonology',
  NEPHROLOGY = 'nephrology',
  ENDOCRINOLOGY = 'endocrinology',
  RHEUMATOLOGY = 'rheumatology',
  HEMATOLOGY = 'hematology',
  ONCOLOGY = 'oncology',
  INFECTIOUS_DISEASE = 'infectious_disease',
  GERIATRICS = 'geriatrics',
  PALLIATIVE_CARE = 'palliative_care',
  PEDIATRICS = 'pediatrics',
  GYNECOLOGY = 'gynecology',
  PSYCHIATRY = 'psychiatry',
  DERMATOLOGY = 'dermatology',
  OPHTHALMOLOGY = 'ophthalmology',
  OTOLARYNGOLOGY = 'otolaryngology',
  UROLOGY = 'urology',
  ALLERGY_IMMUNOLOGY = 'allergy_immunology',
  PAIN_MANAGEMENT = 'pain_management',
  SLEEP_MEDICINE = 'sleep_medicine',
  OCCUPATIONAL_MEDICINE = 'occupational_medicine',
  PREVENTIVE_MEDICINE = 'preventive_medicine'
}

// Display names for better readability
export const SpecializationDisplayNames: Record<MedicalSpecialization, string> = {
  [MedicalSpecialization.GENERAL_PRACTICE]: 'General Practice',
  [MedicalSpecialization.CARDIOLOGY]: 'Cardiology',
  [MedicalSpecialization.NEUROLOGY]: 'Neurology',
  [MedicalSpecialization.GASTROENTEROLOGY]: 'Gastroenterology',
  [MedicalSpecialization.PULMONOLOGY]: 'Pulmonology',
  [MedicalSpecialization.NEPHROLOGY]: 'Nephrology',
  [MedicalSpecialization.ENDOCRINOLOGY]: 'Endocrinology',
  [MedicalSpecialization.RHEUMATOLOGY]: 'Rheumatology',
  [MedicalSpecialization.HEMATOLOGY]: 'Hematology',
  [MedicalSpecialization.ONCOLOGY]: 'Oncology',
  [MedicalSpecialization.INFECTIOUS_DISEASE]: 'Infectious Disease',
  [MedicalSpecialization.GERIATRICS]: 'Geriatrics',
  [MedicalSpecialization.PALLIATIVE_CARE]: 'Palliative Care',
  [MedicalSpecialization.PEDIATRICS]: 'Pediatrics',
  [MedicalSpecialization.GYNECOLOGY]: 'Gynecology',
  [MedicalSpecialization.PSYCHIATRY]: 'Psychiatry',
  [MedicalSpecialization.DERMATOLOGY]: 'Dermatology',
  [MedicalSpecialization.OPHTHALMOLOGY]: 'Ophthalmology',
  [MedicalSpecialization.OTOLARYNGOLOGY]: 'Otolaryngology (ENT)',
  [MedicalSpecialization.UROLOGY]: 'Urology',
  [MedicalSpecialization.ALLERGY_IMMUNOLOGY]: 'Allergy & Immunology',
  [MedicalSpecialization.PAIN_MANAGEMENT]: 'Pain Management',
  [MedicalSpecialization.SLEEP_MEDICINE]: 'Sleep Medicine',
  [MedicalSpecialization.OCCUPATIONAL_MEDICINE]: 'Occupational Medicine',
  [MedicalSpecialization.PREVENTIVE_MEDICINE]: 'Preventive Medicine'
}; 